/*
Nexus Repository Manager REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.76.0-03
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nexus

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CargoGroupRepositoryApiRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CargoGroupRepositoryApiRequest{}

// CargoGroupRepositoryApiRequest struct for CargoGroupRepositoryApiRequest
type CargoGroupRepositoryApiRequest struct {
	// A unique identifier for this repository
	Name string `json:"name" validate:"regexp=^[a-zA-Z0-9\\\\-]{1}[a-zA-Z0-9_\\\\-\\\\.]*$"`
	// Whether this repository accepts incoming requests
	Online bool `json:"online"`
	Storage StorageAttributes `json:"storage"`
	Group GroupAttributes `json:"group"`
	Cargo *CargoAttributes `json:"cargo,omitempty"`
}

type _CargoGroupRepositoryApiRequest CargoGroupRepositoryApiRequest

// NewCargoGroupRepositoryApiRequest instantiates a new CargoGroupRepositoryApiRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCargoGroupRepositoryApiRequest(name string, online bool, storage StorageAttributes, group GroupAttributes) *CargoGroupRepositoryApiRequest {
	this := CargoGroupRepositoryApiRequest{}
	this.Name = name
	this.Online = online
	this.Storage = storage
	this.Group = group
	return &this
}

// NewCargoGroupRepositoryApiRequestWithDefaults instantiates a new CargoGroupRepositoryApiRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCargoGroupRepositoryApiRequestWithDefaults() *CargoGroupRepositoryApiRequest {
	this := CargoGroupRepositoryApiRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CargoGroupRepositoryApiRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CargoGroupRepositoryApiRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CargoGroupRepositoryApiRequest) SetName(v string) {
	o.Name = v
}

// GetOnline returns the Online field value
func (o *CargoGroupRepositoryApiRequest) GetOnline() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Online
}

// GetOnlineOk returns a tuple with the Online field value
// and a boolean to check if the value has been set.
func (o *CargoGroupRepositoryApiRequest) GetOnlineOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Online, true
}

// SetOnline sets field value
func (o *CargoGroupRepositoryApiRequest) SetOnline(v bool) {
	o.Online = v
}

// GetStorage returns the Storage field value
func (o *CargoGroupRepositoryApiRequest) GetStorage() StorageAttributes {
	if o == nil {
		var ret StorageAttributes
		return ret
	}

	return o.Storage
}

// GetStorageOk returns a tuple with the Storage field value
// and a boolean to check if the value has been set.
func (o *CargoGroupRepositoryApiRequest) GetStorageOk() (*StorageAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Storage, true
}

// SetStorage sets field value
func (o *CargoGroupRepositoryApiRequest) SetStorage(v StorageAttributes) {
	o.Storage = v
}

// GetGroup returns the Group field value
func (o *CargoGroupRepositoryApiRequest) GetGroup() GroupAttributes {
	if o == nil {
		var ret GroupAttributes
		return ret
	}

	return o.Group
}

// GetGroupOk returns a tuple with the Group field value
// and a boolean to check if the value has been set.
func (o *CargoGroupRepositoryApiRequest) GetGroupOk() (*GroupAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Group, true
}

// SetGroup sets field value
func (o *CargoGroupRepositoryApiRequest) SetGroup(v GroupAttributes) {
	o.Group = v
}

// GetCargo returns the Cargo field value if set, zero value otherwise.
func (o *CargoGroupRepositoryApiRequest) GetCargo() CargoAttributes {
	if o == nil || IsNil(o.Cargo) {
		var ret CargoAttributes
		return ret
	}
	return *o.Cargo
}

// GetCargoOk returns a tuple with the Cargo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CargoGroupRepositoryApiRequest) GetCargoOk() (*CargoAttributes, bool) {
	if o == nil || IsNil(o.Cargo) {
		return nil, false
	}
	return o.Cargo, true
}

// HasCargo returns a boolean if a field has been set.
func (o *CargoGroupRepositoryApiRequest) HasCargo() bool {
	if o != nil && !IsNil(o.Cargo) {
		return true
	}

	return false
}

// SetCargo gets a reference to the given CargoAttributes and assigns it to the Cargo field.
func (o *CargoGroupRepositoryApiRequest) SetCargo(v CargoAttributes) {
	o.Cargo = &v
}

func (o CargoGroupRepositoryApiRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CargoGroupRepositoryApiRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["online"] = o.Online
	toSerialize["storage"] = o.Storage
	toSerialize["group"] = o.Group
	if !IsNil(o.Cargo) {
		toSerialize["cargo"] = o.Cargo
	}
	return toSerialize, nil
}

func (o *CargoGroupRepositoryApiRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"online",
		"storage",
		"group",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCargoGroupRepositoryApiRequest := _CargoGroupRepositoryApiRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCargoGroupRepositoryApiRequest)

	if err != nil {
		return err
	}

	*o = CargoGroupRepositoryApiRequest(varCargoGroupRepositoryApiRequest)

	return err
}

type NullableCargoGroupRepositoryApiRequest struct {
	value *CargoGroupRepositoryApiRequest
	isSet bool
}

func (v NullableCargoGroupRepositoryApiRequest) Get() *CargoGroupRepositoryApiRequest {
	return v.value
}

func (v *NullableCargoGroupRepositoryApiRequest) Set(val *CargoGroupRepositoryApiRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCargoGroupRepositoryApiRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCargoGroupRepositoryApiRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCargoGroupRepositoryApiRequest(val *CargoGroupRepositoryApiRequest) *NullableCargoGroupRepositoryApiRequest {
	return &NullableCargoGroupRepositoryApiRequest{value: val, isSet: true}
}

func (v NullableCargoGroupRepositoryApiRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCargoGroupRepositoryApiRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


