/*
Nexus Repository Manager REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.76.0-03
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nexus

import (
	"encoding/json"
)

// checks if the MaliciousRiskSummaryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MaliciousRiskSummaryResponse{}

// MaliciousRiskSummaryResponse struct for MaliciousRiskSummaryResponse
type MaliciousRiskSummaryResponse struct {
	CountByEcosystem []MaliciousRiskCountByEcosystem `json:"countByEcosystem,omitempty"`
	TotalMaliciousRiskCount *int64 `json:"totalMaliciousRiskCount,omitempty"`
	TotalProxyRepositoryCount *int64 `json:"totalProxyRepositoryCount,omitempty"`
	QuarantineEnabledRepositoryCount *int64 `json:"quarantineEnabledRepositoryCount,omitempty"`
	HdsError *bool `json:"hdsError,omitempty"`
}

// NewMaliciousRiskSummaryResponse instantiates a new MaliciousRiskSummaryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMaliciousRiskSummaryResponse() *MaliciousRiskSummaryResponse {
	this := MaliciousRiskSummaryResponse{}
	return &this
}

// NewMaliciousRiskSummaryResponseWithDefaults instantiates a new MaliciousRiskSummaryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMaliciousRiskSummaryResponseWithDefaults() *MaliciousRiskSummaryResponse {
	this := MaliciousRiskSummaryResponse{}
	return &this
}

// GetCountByEcosystem returns the CountByEcosystem field value if set, zero value otherwise.
func (o *MaliciousRiskSummaryResponse) GetCountByEcosystem() []MaliciousRiskCountByEcosystem {
	if o == nil || IsNil(o.CountByEcosystem) {
		var ret []MaliciousRiskCountByEcosystem
		return ret
	}
	return o.CountByEcosystem
}

// GetCountByEcosystemOk returns a tuple with the CountByEcosystem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaliciousRiskSummaryResponse) GetCountByEcosystemOk() ([]MaliciousRiskCountByEcosystem, bool) {
	if o == nil || IsNil(o.CountByEcosystem) {
		return nil, false
	}
	return o.CountByEcosystem, true
}

// HasCountByEcosystem returns a boolean if a field has been set.
func (o *MaliciousRiskSummaryResponse) HasCountByEcosystem() bool {
	if o != nil && !IsNil(o.CountByEcosystem) {
		return true
	}

	return false
}

// SetCountByEcosystem gets a reference to the given []MaliciousRiskCountByEcosystem and assigns it to the CountByEcosystem field.
func (o *MaliciousRiskSummaryResponse) SetCountByEcosystem(v []MaliciousRiskCountByEcosystem) {
	o.CountByEcosystem = v
}

// GetTotalMaliciousRiskCount returns the TotalMaliciousRiskCount field value if set, zero value otherwise.
func (o *MaliciousRiskSummaryResponse) GetTotalMaliciousRiskCount() int64 {
	if o == nil || IsNil(o.TotalMaliciousRiskCount) {
		var ret int64
		return ret
	}
	return *o.TotalMaliciousRiskCount
}

// GetTotalMaliciousRiskCountOk returns a tuple with the TotalMaliciousRiskCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaliciousRiskSummaryResponse) GetTotalMaliciousRiskCountOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalMaliciousRiskCount) {
		return nil, false
	}
	return o.TotalMaliciousRiskCount, true
}

// HasTotalMaliciousRiskCount returns a boolean if a field has been set.
func (o *MaliciousRiskSummaryResponse) HasTotalMaliciousRiskCount() bool {
	if o != nil && !IsNil(o.TotalMaliciousRiskCount) {
		return true
	}

	return false
}

// SetTotalMaliciousRiskCount gets a reference to the given int64 and assigns it to the TotalMaliciousRiskCount field.
func (o *MaliciousRiskSummaryResponse) SetTotalMaliciousRiskCount(v int64) {
	o.TotalMaliciousRiskCount = &v
}

// GetTotalProxyRepositoryCount returns the TotalProxyRepositoryCount field value if set, zero value otherwise.
func (o *MaliciousRiskSummaryResponse) GetTotalProxyRepositoryCount() int64 {
	if o == nil || IsNil(o.TotalProxyRepositoryCount) {
		var ret int64
		return ret
	}
	return *o.TotalProxyRepositoryCount
}

// GetTotalProxyRepositoryCountOk returns a tuple with the TotalProxyRepositoryCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaliciousRiskSummaryResponse) GetTotalProxyRepositoryCountOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalProxyRepositoryCount) {
		return nil, false
	}
	return o.TotalProxyRepositoryCount, true
}

// HasTotalProxyRepositoryCount returns a boolean if a field has been set.
func (o *MaliciousRiskSummaryResponse) HasTotalProxyRepositoryCount() bool {
	if o != nil && !IsNil(o.TotalProxyRepositoryCount) {
		return true
	}

	return false
}

// SetTotalProxyRepositoryCount gets a reference to the given int64 and assigns it to the TotalProxyRepositoryCount field.
func (o *MaliciousRiskSummaryResponse) SetTotalProxyRepositoryCount(v int64) {
	o.TotalProxyRepositoryCount = &v
}

// GetQuarantineEnabledRepositoryCount returns the QuarantineEnabledRepositoryCount field value if set, zero value otherwise.
func (o *MaliciousRiskSummaryResponse) GetQuarantineEnabledRepositoryCount() int64 {
	if o == nil || IsNil(o.QuarantineEnabledRepositoryCount) {
		var ret int64
		return ret
	}
	return *o.QuarantineEnabledRepositoryCount
}

// GetQuarantineEnabledRepositoryCountOk returns a tuple with the QuarantineEnabledRepositoryCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaliciousRiskSummaryResponse) GetQuarantineEnabledRepositoryCountOk() (*int64, bool) {
	if o == nil || IsNil(o.QuarantineEnabledRepositoryCount) {
		return nil, false
	}
	return o.QuarantineEnabledRepositoryCount, true
}

// HasQuarantineEnabledRepositoryCount returns a boolean if a field has been set.
func (o *MaliciousRiskSummaryResponse) HasQuarantineEnabledRepositoryCount() bool {
	if o != nil && !IsNil(o.QuarantineEnabledRepositoryCount) {
		return true
	}

	return false
}

// SetQuarantineEnabledRepositoryCount gets a reference to the given int64 and assigns it to the QuarantineEnabledRepositoryCount field.
func (o *MaliciousRiskSummaryResponse) SetQuarantineEnabledRepositoryCount(v int64) {
	o.QuarantineEnabledRepositoryCount = &v
}

// GetHdsError returns the HdsError field value if set, zero value otherwise.
func (o *MaliciousRiskSummaryResponse) GetHdsError() bool {
	if o == nil || IsNil(o.HdsError) {
		var ret bool
		return ret
	}
	return *o.HdsError
}

// GetHdsErrorOk returns a tuple with the HdsError field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaliciousRiskSummaryResponse) GetHdsErrorOk() (*bool, bool) {
	if o == nil || IsNil(o.HdsError) {
		return nil, false
	}
	return o.HdsError, true
}

// HasHdsError returns a boolean if a field has been set.
func (o *MaliciousRiskSummaryResponse) HasHdsError() bool {
	if o != nil && !IsNil(o.HdsError) {
		return true
	}

	return false
}

// SetHdsError gets a reference to the given bool and assigns it to the HdsError field.
func (o *MaliciousRiskSummaryResponse) SetHdsError(v bool) {
	o.HdsError = &v
}

func (o MaliciousRiskSummaryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MaliciousRiskSummaryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CountByEcosystem) {
		toSerialize["countByEcosystem"] = o.CountByEcosystem
	}
	if !IsNil(o.TotalMaliciousRiskCount) {
		toSerialize["totalMaliciousRiskCount"] = o.TotalMaliciousRiskCount
	}
	if !IsNil(o.TotalProxyRepositoryCount) {
		toSerialize["totalProxyRepositoryCount"] = o.TotalProxyRepositoryCount
	}
	if !IsNil(o.QuarantineEnabledRepositoryCount) {
		toSerialize["quarantineEnabledRepositoryCount"] = o.QuarantineEnabledRepositoryCount
	}
	if !IsNil(o.HdsError) {
		toSerialize["hdsError"] = o.HdsError
	}
	return toSerialize, nil
}

type NullableMaliciousRiskSummaryResponse struct {
	value *MaliciousRiskSummaryResponse
	isSet bool
}

func (v NullableMaliciousRiskSummaryResponse) Get() *MaliciousRiskSummaryResponse {
	return v.value
}

func (v *NullableMaliciousRiskSummaryResponse) Set(val *MaliciousRiskSummaryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMaliciousRiskSummaryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMaliciousRiskSummaryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMaliciousRiskSummaryResponse(val *MaliciousRiskSummaryResponse) *NullableMaliciousRiskSummaryResponse {
	return &NullableMaliciousRiskSummaryResponse{value: val, isSet: true}
}

func (v NullableMaliciousRiskSummaryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMaliciousRiskSummaryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


